project:
  type: website
  output-dir: docs

website:
  title: "Odyssée — Le Monolithe"
  
  navbar:
    false



title: "Odyssée — Le Monolithe"
author: "Charles Klein"

description: >
  Publication photographique de Charles Klein autour de la matière,
  de la mémoire et des traces humaines.

keywords:
  - photographie d'auteur
  - Charles Klein
  - Odyssée
  - Le Monolithe
  - photographie contemporaine

canonical: "https://charleskleinpublications.github.io/xxx/"


format:

  html:
    theme: none
    css:
      - css/monolithe.css

    include-after-body: 
     text: |
      <script src="js/navigation.js"></script>

    toc: false
    page-layout: full