project:
  type: website
  output-dir: docs

website:
  title: "Odyssée — Le Monolithe"
  
  navbar:
    false


format:

  html:
    theme: none
    css:
      - css/monolithe.css

    include-after-body: 
     text: |
      <script src="js/navigation.js"></script>

    toc: false
    page-layout: full